server:
  port: 9002

spring:
  boot:
    admin:
      client:
        url: "http://localhost:9004"
  application:
    name: Gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/libingteam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  profiles:
    active: core
  #静态配置路由
  cloud:
    gateway:
      #开启SpringCloud Gateway的注册中心发现配置，开启后可自动从服务注册中心拉取服务列表，通过各个服务的spring.application.name作为前缀进行转发，该配置默认为false。
      discovery:
        locator:
          enabled: true
          url-expression:
      #自己配置想要的路由
#      routes:
#        - id: path_route
#          uri: lb://ProviderA
#          predicates:
#            - Path=/index/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  instance:
    health-check-url-path: actuator/health
    status-page-url-path: actuator/info
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  level:
    com.zjy: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
